version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "event-consumer-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-11rw23fibiiyy"
s3_prefix = "event-consumer-test"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
